### ISSUE TITLE
Configurar ambiente de desenvolvimento para 2021.1-PC-GO1-Archives 

### ISSUE THREAD

**Issue by darmsDD** [fga-eps-mds/2021.1-PC-GO1#16]
## Descrição
O objetivo dessa issue é realizar a configuração do ambiente de produção no repositório 2021.1-PC-GO1-Archives

## Tarefas
- [x]  Criar  DockerFile
- [x]  Criar arquivo do Docker-Compose
- [x]  Configurar o SonarCloud
- [x]  Criar testes de integração

**Comment by bielrossi15** [comment]
Ambiente criado com todos os checks completos.
