### ISSUE TITLE
Adicionar links na wiki e alterar pr template

### ISSUE THREAD

**Issue by darmsDD** [fga-eps-mds/2021.1-PC-GO1#85]
## Descrição
É necessário adicionar na wiki os links das histórias de usuário que estão como issues no github e alterar template de PR para colocar prints do que foi feito.

## Tarefas

- [x]  Adicionar links na wiki
- [x] Alterar pr template

**Comment by bielrossi15** [comment]
Ambas as tarefas foram resolvidas
